version: "3"

services:
  mongodb:
    image: mongo:latest
    environment:
      - MONGODB_DATABASE="day30"
    ports:
      - 27017:27017
  redis:
    container_name: test-redis
    image: redis
    ports:
      - '6379:6379'
    restart: always